import { Attribute, CharacterSheet } from '@/types/contracts';

export const ATTRIBUTES: Attribute[] = [
  Attribute.STR,
  Attribute.DEX,
  Attribute.CON,
  Attribute.INT,
  Attribute.WIS,
  Attribute.CHA,
];

export const SKILLS_LIST = [
  'Acrobatics',
  'Appraise',
  'Bluff',
  'Climb',
  'Craft',
  'Diplomacy',
  'Disable Device',
  'Disguise',
  'Escape Artist',
  'Fly',
  'Handle Animal',
  'Heal',
  'Intimidate',
  'Knowledge (Arcana)',
  'Knowledge (Dungeoneering)',
  'Knowledge (Engineering)',
  'Knowledge (Geography)',
  'Knowledge (History)',
  'Knowledge (Local)',
  'Knowledge (Nature)',
  'Knowledge (Nobility)',
  'Knowledge (Planes)',
  'Knowledge (Religion)',
  'Linguistics',
  'Perception',
  'Perform',
  'Profession',
  'Ride',
  'Sense Motive',
  'Sleight of Hand',
  'Spellcraft',
  'Stealth',
  'Survival',
  'Swim',
  'Use Magic Device',
];

export const NEW_CHARACTER_TEMPLATE: Omit<CharacterSheet, 'name' | 'race' | 'characterClass'> = {
  level: 1,
  xp: 0,
  alignment: 'True Neutral',
  background: 'Adventurer',
  hp: 10,
  maxHp: 10,
  temporaryHp: 0,
  hitDice: { total: 1, current: 1, die: '1d10' },
  deathSaves: { successes: 0, failures: 0 },
  armorClass: 10,
  resistances: [],
  immunities: [],
  vulnerabilities: [],
  initiative: 0,
  speed: { walk: 30 },
  proficiencyBonus: 2,
  inspiration: false,

  attributes: {
    [Attribute.STR]: 10,
    [Attribute.DEX]: 10,
    [Attribute.CON]: 10,
    [Attribute.INT]: 10,
    [Attribute.WIS]: 10,
    [Attribute.CHA]: 10,
  },
  savingThrows: {
    fortitude: 0,
    reflex: 0,
    will: 0,
  },
  conditions: [],
  skills: SKILLS_LIST.reduce<Record<string, number>>((acc, skill) => {
    acc[skill] = 0;
    return acc;
  }, {}),
  skillDetails: [],
  talents: [],
  expertises: [],
  equipment: [],

  features: [],
  currency: { cp: 0, sp: 0, ep: 0, gp: 10, pp: 0 },
  appearance: {
    age: 'Unknown',
    height: '5\'8"',
    weight: '160 lbs',
    eyes: 'Brown',
    skin: 'Fair',
    hair: 'Brown',
    description: '',
  },
  personality: {
    traits: '',
    ideals: '',
    bonds: '',
    flaws: '',
  },
  backstory: '',
  alliesAndOrganizations: '',
  treasure: '',
  backgroundDetails: { origin: '', upbringing: '', motivation: '', keyEvents: [] },
  advancementPoints: { ability: 0, skill: 0, talent: 0 },
  resources: [], // Renamed from resourcePools
};
